vti_encoding:SR|utf8-nl
vti_author:SR|WBS0030\\Administrator
vti_modifiedby:SR|WBS0030\\Administrator
vti_timelastmodified:TR|18 Dec 2008 00:45:12 -0000
vti_timecreated:TR|20 Nov 2008 02:55:28 -0000
vti_lineageid:SR|{DAA27A64-B92E-40DB-8222-BB6BA99A4EFD}
vti_extenderversion:SR|5.0.2.6790
vti_backlinkinfo:VX|
vti_nexttolasttimemodified:TW|20 Nov 2008 02:55:28 -0000
vti_cacheddtm:TX|18 Dec 2008 00:45:12 -0000
vti_filesize:IR|6846
